"""
tools/extract_css.py — pull the portable house style out of app.py.

app.py carries ~1,360 lines of CSS inline. Roughly half is Streamlit plumbing
(selectors reaching into data-testid internals to make its widgets behave) and
the rest is Nabbly's actual design: the :root tokens and the .gr-* components
that every card, pill, nav and hero is built from.

The board service needs the second half and must never carry the first. Copying
it by hand would guarantee the two drift, and "why does the new board look
slightly off" is exactly the bug nobody can find. So it is extracted, with the
Streamlit-only rules dropped by rule rather than by eye.

Run it whenever app.py's styling changes:

    python tools/extract_css.py

Writes web/static/nabbly.css. Deliberately NOT run at import time — a build
step that runs on every boot is a build step that fails on some boot.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP = os.path.join(HERE, "app.py")
OUT = os.path.join(HERE, "web", "static", "nabbly.css")

# A selector mentioning any of these is reaching into Streamlit's own DOM and
# means nothing in plain HTML.
STREAMLIT_ONLY = ("data-testid", "stApp", "stMain", "stSidebar", "stToolbar",
                  "stDecoration", "stStatusWidget", "streamlit", "stMarkdown",
                  "baseweb", "emotion", "stButton", "stTextInput", "stExpander",
                  "stSelectbox", "stMultiSelect", "stForm", "stColumn",
                  "stVerticalBlock", "stHorizontalBlock", "stElementContainer",
                  "stAppViewContainer", "stHeader", "stSpinner", "stAlert",
                  "stCheckbox", "stSegmentedControl", "stFileUploader",
                  "stRadio", "stSlider", "stTabs", "stDataFrame", "stMetric")


def css_block(src: str) -> str:
    m = re.search(r"<style>(.*?)</style>", src, re.S)
    if not m:
        sys.exit("no <style> block found in app.py")
    return m.group(1)


def split_rules(css: str):
    """Yield (selector, body) plus @media blocks kept whole."""
    i, n = 0, len(css)
    while i < n:
        # comments
        if css.startswith("/*", i):
            j = css.find("*/", i + 2)
            i = n if j < 0 else j + 2
            continue
        if css[i] in " \n\r\t":
            i += 1
            continue
        if css.startswith("@", i):
            brace = css.find("{", i)
            if brace < 0:
                break
            depth, j = 1, brace + 1
            while j < n and depth:
                if css[j] == "{":
                    depth += 1
                elif css[j] == "}":
                    depth -= 1
                j += 1
            yield css[i:brace].strip(), css[brace:j]
            i = j
            continue
        brace = css.find("{", i)
        if brace < 0:
            break
        end = css.find("}", brace)
        if end < 0:
            break
        yield css[i:brace].strip(), css[brace:end + 1]
        i = end + 1


def portable(selector: str, body: str) -> bool:
    blob = selector + body
    return not any(tok in blob for tok in STREAMLIT_ONLY)


def main():
    src = open(APP, encoding="utf-8").read()
    css = css_block(src)
    kept, dropped = [], 0
    for sel, body in split_rules(css):
        if portable(sel, body):
            kept.append(f"{sel}{body}")
        else:
            dropped += 1
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    header = (
        "/* GENERATED by tools/extract_css.py from app.py — do not edit here.\n"
        " * Nabbly's design tokens and .gr-* components, shared by the\n"
        " * Streamlit app and the board service so the two cannot drift.\n"
        " * Streamlit-internal selectors are dropped; everything else is\n"
        " * byte-for-byte what app.py serves. */\n\n")
    open(OUT, "w", encoding="utf-8").write(header + "\n".join(kept) + "\n")
    print(f"kept {len(kept)} rules, dropped {dropped} Streamlit-only rules")
    print(f"-> {OUT} ({os.path.getsize(OUT)/1024:.0f} KB)")
    for name in ("--amber", ".gr-card", ".gr-nav", ".gr-hero", ".gr-cat",
                 ".gr-title", ".gr-pill"):
        print(f"   {name:<12} {'present' if name in open(OUT).read() else 'MISSING'}")


if __name__ == "__main__":
    main()
