"""
make_alert_open.py — the beat the walkthrough was missing.

walkthrough.mp4 opens with someone already on the board, which skips the part
the product is actually selling. Nobody sits on a job board waiting. The gig
lands, Nabbly tells you, and you arrive because it told you. This renders that
first beat and joins it to the existing walkthrough.

THE ALERT IS TYPESET, NOT SCREEN-GRABBED — the same honest seam make_walkthrough
already documents for /draft. Capturing a real one would mean wiring a webhook
to a throwaway Slack and filming a notification, and the wording would be
identical because it is taken from alerts.py's own formatter:

    ⚡ *{n} new matching gig{s} on Nabbly:*
    *{title}*
    {job_type} · {size_tier} budget · {source}

Two deliberate departures from that string, both to avoid inventing anything:
  - the bolt is dropped. PIL cannot render Apple's colour emoji at arbitrary
    sizes, and drawing a substitute bolt would be a different mark than the one
    the alert actually sends.
  - the source is dropped. The reply cut records the gig's field and budget but
    not which board it came from, and naming one would be a guess.

The gig named here MUST match the one the walkthrough answers, or the two
halves are about different jobs. It is asserted against make_demo_video's own
constant rather than copied, so the two cannot drift apart silently.

Writes a NEW file rather than overwriting walkthrough.mp4: the demo cuts are
regenerated by other passes, and this beat should never be the reason one of
them is lost.

Run:  .venv/bin/python tools/make_alert_open.py
Out:  brand/posts/demo/walkthrough-full.mp4
"""
import json
import sys
from pathlib import Path

import imageio.v2 as iio
import numpy as np
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import make_post as mp                                    # noqa: E402
import make_demo_video as dv                              # noqa: E402

OUT = ROOT / "brand" / "posts" / "demo"
# 9:16 default, same as the social cut. Pass WxH to open the landscape demo;
# the source walkthrough and the output are picked to match, so the beat never
# gets stapled onto a video of a different shape.
W, H, FPS = 1080, 1920, 30

# The gig the second half answers. Read from the reply cut's own module so a
# change there fails loudly here instead of producing a video whose alert
# announces one job and whose reply writes about another.
GIG = dv.GIG

# The field and budget come from the CAPTURE, not from a constant here. They
# were hardcoded, and when the demo changed gig the alert kept announcing
# "Design / creative" over a Product / PM posting — the kind of detail nobody
# notices until the one person who knows the board does.
def meta_from(frames_dir: Path | None) -> str:
    f = (frames_dir / "gig.json") if frames_dir else None
    if f and f.exists():
        pills = json.loads(f.read_text()).get("pills", [])
        # "Free account needed to apply" is an apply-wall note, not a fact
        # about the gig, and it has no business in a notification.
        keep = [p for p in pills if "account" not in p.lower()][:2]
        if keep:
            return "  ·  ".join(keep)
    return "Product / PM  ·  Medium budget"

META = ""                       # set in __main__ from the capture
HEAD = "1 new matching gig on Nabbly"

# Beats, in frames. The card is on screen long enough to read twice: someone
# scrolling past a demo reads slower than someone who wrote it.
FADE_IN, HOLD, SEAM = 14, 74, 14
RISE = 26                      # px the card travels while it fades up


def ground():
    """Near-black with one soft amber light behind where the card sits."""
    yy, xx = np.mgrid[0:H, 0:W].astype(np.float32)
    cx, cy, r = W * 0.5, H * 0.44, W * 0.62
    d = ((xx - cx) / r) ** 2 + ((yy - cy) / r) ** 2
    glow = np.exp(-d * 1.6)[..., None] * np.array(mp.AMBER, np.float32) * 0.13
    return np.clip(np.array(mp.BG, np.float32) + glow, 0, 255)


def card(alpha: float, dy: int) -> Image.Image:
    """
    The notification itself. Supersampled so the rounded corners and the
    hairline survive being drawn once and composited, same as the posts.
    """
    ss = 2
    # THE TITLE WRAPS. Real gig titles are not short — "Senior Technical
    # Program Manager, GTM Transformation" ran off the end of a fixed card and
    # was clipped mid-word, which reads as a broken notification rather than a
    # long job title. It is measured, wrapped to the card's own width, and the
    # card grows by a line if it needs to.
    cw = 892
    f_gig = mp.font(43, "Bold")
    probe = ImageDraw.Draw(Image.new("RGB", (8, 8)))
    words, lines, cur = GIG.split(), [], ""
    for word in words:
        trial = f"{cur} {word}".strip()
        if probe.textlength(trial, font=f_gig) <= cw - 80:
            cur = trial
        else:
            lines.append(cur)
            cur = word
    if cur:
        lines.append(cur)
    ch = 348 + max(0, len(lines) - 1) * 52
    im = Image.new("RGBA", (cw * ss, ch * ss), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    a = int(round(255 * alpha))
    d.rounded_rectangle([0, 0, cw * ss - 1, ch * ss - 1], radius=30 * ss,
                        fill=(21, 24, 29, a), outline=(47, 52, 61, a),
                        width=2 * ss)
    im = im.resize((cw, ch), Image.LANCZOS)
    d = ImageDraw.Draw(im)

    mark = mp.nabbly_mark(56)
    if alpha < 1:
        mark.putalpha(mark.getchannel("A").point(lambda v: int(v * alpha)))
    im.paste(mark, (40, 38), mark)

    fade = lambda c: tuple(list(c) + [a])                 # noqa: E731
    d.text((112, 44), "Nabbly", font=mp.font(31, "Semibold"), fill=fade(mp.BODY))
    d.text((112, 78), "now", font=mp.font(25, "Regular", mp.ARIAL), fill=fade(mp.DIM))

    d.text((40, 148), HEAD, font=mp.font(27, "Semibold"), fill=fade(mp.HOT))
    y = 208
    for ln in lines:
        d.text((40, y), ln, font=f_gig, fill=fade(mp.BODY))
        y += 52
    d.text((40, y + 14), META, font=mp.font(28, "Regular", mp.ARIAL),
           fill=fade(mp.GREY))
    return im


def main():
    wide = W > H
    src = OUT / ("walkthrough-wide.mp4" if wide else "walkthrough.mp4")
    assert src.exists(), f"missing {src}; run make_walkthrough.py first"

    bg = ground()
    out = OUT / ("demo-full-wide.mp4" if wide else "walkthrough-full.mp4")
    w = iio.get_writer(out, fps=FPS, codec="libx264", quality=9,
                       macro_block_size=1, ffmpeg_params=["-pix_fmt", "yuv420p"])

    def smooth(t):
        t = max(0.0, min(1.0, t))
        return t * t * (3 - 2 * t)

    frames = []
    for i in range(FADE_IN + HOLD):
        t = smooth((i + 1) / FADE_IN) if i < FADE_IN else 1.0
        c = card(t, 0)
        im = Image.fromarray(bg.astype(np.uint8), "RGB")
        x = (W - c.width) // 2
        y = int(round(H * 0.40 - c.height / 2 + RISE * (1 - t)))
        im.paste(c, (x, y), c)
        frames.append(np.asarray(im))

    for f in frames:
        w.append_data(f)
    n = len(frames)

    # Cross-fade the alert into the board, so arriving reads as one motion
    # rather than two clips stapled together.
    reader = iio.get_reader(src)
    last = frames[-1].astype(np.float32)
    for i, frame in enumerate(reader):
        if frame.shape[0] != H or frame.shape[1] != W:
            frame = np.asarray(Image.fromarray(frame).resize((W, H), Image.LANCZOS))
        if i == 0:
            for k in range(SEAM):
                t = (k + 1) / (SEAM + 1)
                w.append_data((last * (1 - t) + frame * t).astype(np.uint8))
                n += 1
        w.append_data(frame)
        n += 1
    reader.close()
    w.close()
    print(f"wrote {out}  {W}x{H}  {n} frames  {n / FPS:.1f}s")
    print(f"  opening beat: {(len(frames) + SEAM) / FPS:.1f}s announcing {GIG!r}")


if __name__ == "__main__":
    # make_alert_open.py [WxH] [frames_dir]
    argv = sys.argv[1:]
    size = next((a for a in argv if "x" in a
                 and all(p.isdigit() for p in a.split("x", 1))), None)
    if size:
        argv.remove(size)
        W, H = (int(v) for v in size.split("x"))
    META = meta_from(Path(argv[0]) if argv else None)
    main()
